#!/bin/bash
# December, 2006 - Gabriel Rojas - Fernando Garcia Bermudez

# Determine the path to this application.
APPDIR=`dirname "$0"`
cd "$APPDIR"
APPDIR="`pwd`"
actual=`date +"%Y-%m-%dT%T"`

#################################################
#################################################
#	TRANSLATIONS
		###### Default = English #####
		txt1="Zenity is not installed, you need zenity >= 2.12.1"
		txt2="HIDDEN-"
		txt3="The trashcan is already empty!"
                txt4="Empty the Trashcan"
                txt5="Confirm Delete:"
                txt6="The trashcan is empty!"
                txt7="Restore ALL items in trashcan?"
                txt8="Move to trash"
                txt9="Delete this item(s)?"
                txt10="You can't move"
                txt11="to the Trash because of insufficient permissions."
                txt12="Do you still want to delete it?" 
                txt13="The item"
                txt14="is a Symbolic Link.
This will move the Symbolic Link to the Trash and leave the original item  alone.
Do you want to continue?"
                txt15="There is one or more Desktop shortcuts pointing to"
                txt16="This will move the original item to the Trash and remove the shortcut(s) from the Desktop.
Do you want to continue?"
                txt17="There is one or more Panel shortcuts pointing to"
                txt18="This will move the original item to the Trash and remove the shortcut(s) from the Panel.
Do you want to continue?"
                appinfo1="Deleted on:"
                appinfo2="Origin:"
                appinfo3="Type"
                appinfo4="Deleted"
                appinfo5="Origin"
                appinfo6="Restore"
                appinfo7="Delete"

	case $LANG in
		######## Español ########
		es* )
                    # AppRun strings
		txt1="Zenity no esta instalado, necesitas >= 2.12.1"
		txt2="OCULTO-"
		txt3="La papelera ya esta vacia!"
                txt4="Vaciar la Papelera"
                txt5="Confirmar eliminacion:"
                txt6="La papelera esta vacia!"
                txt7="Restaurar TODOS los items de la papelera?"
                txt8="Mover a Papelera"
                txt9="Borrar estos items?"
                txt10="No puedes mover"
                txt11="a la papelera por permisos insuficientes."
                txt12="Todavia quieres eliminarlos?" 
                txt13="El item"
                txt14="es un enlace simbolico.
La papelera movera el enlace y dejara el elemento.
Deseas continuar?"
                txt15="Hay uno o mas accesos de escritorio apuntando a"
                txt16="La papelera movera el item y el acceso del pinboard.
Deseas continuar?"
                txt17="Hay uno o mas accesos de panel apuntando a"
                txt18="La papelera movera el item y el acceso del panel.
Deseas continuar?"
                appinfo1="Borrado el:"
                appinfo2="Origen:"
                appinfo3="Tipo"
                appinfo4="Eliminacion"
                appinfo5="Origen"
                appinfo6="Restaurar"
                appinfo7="Borrar"
	esac

### End of Translations ###
###########################
###########################


####### Set Trash Icon ###########
##################################

if test -e "$HOME/.gtkrc-2.0"; then
theme=`grep gtk-theme-name $HOME/.gtkrc-2.0 | sed -e s/'gtk-theme-name'// -e s/' '// -e s/'='// -e s/'"'// -e s/'"'//`
theme=`expr "$theme" : '[[:space:]]*\(.*\)[[:space:]]*$'`
if  [ "$theme" = "" ];then
theme=`grep gtk-fallback-icon-theme /etc/gtk-2.0/gtkrc | sed -e s/'gtk-fallback-icon-theme'// -e s/' '// -e s/'='// -e s/'"'// -e s/'"'//`
theme=`expr "$theme" : '[[:space:]]*\(.*\)[[:space:]]*$'`
fi
else
theme=`grep gtk-fallback-icon-theme /etc/gtk-2.0/gtkrc | sed -e s/'gtk-fallback-icon-theme'// -e s/' '// -e s/'='// -e s/'"'// -e s/'"'//`
theme=`expr "$theme" : '[[:space:]]*\(.*\)[[:space:]]*$'`
fi

if  [ "$XDG_DATA_DIRS" = "" ]; then
    XDG_DATA_DIRS="/usr/share"
fi

if test -e "$XDG_DATA_DIRS/icons/$theme/scalable"; then

gnome=`find "$XDG_DATA_DIRS/icons/$theme/scalable/filesystems" -name gnome*`

if [ "$gnome" != "" ]; then

empty_icon="$XDG_DATA_DIRS/icons/$theme/scalable/filesystems/gnome-fs-trash-empty.svg"
full_icon="$XDG_DATA_DIRS/icons/$theme/scalable/filesystems/gnome-fs-trash-full.svg"

else

empty_icon="$XDG_DATA_DIRS/icons/$theme/scalable/filesystems/fs-trash-empty.svg"
full_icon="$XDG_DATA_DIRS/icons/$theme/scalable/filesystems/fs-trash-full.svg"

fi

else

gnome=`find "$XDG_DATA_DIRS/icons/$theme/48x48/filesystems" -name gnome*`

if [ "$gnome" != "" ]; then

empty_icon="$XDG_DATA_DIRS/icons/$theme/48x48/filesystems/gnome-fs-trash-empty.png"
full_icon="$XDG_DATA_DIRS/icons/$theme/48x48/filesystems/gnome-fs-trash-full.png"

else

empty_icon="$XDG_DATA_DIRS/icons/$theme/48x48/filesystems/fs-trash-empty.png"
full_icon="$XDG_DATA_DIRS/icons/$theme/48x48/filesystems/fs-trash-full.png"

fi

fi

if [ ! -e "$empty_icon" ] || [ ! -e "$full_icon" ]; then

if test -e "$XDG_DATA_DIRS/icons/hicolor/scalable"; then

gnome=`find "$XDG_DATA_DIRS/icons/hicolor/scalable/filesystems" -name gnome*`

if [ "$gnome" != "" ]; then

empty_icon="$XDG_DATA_DIRS/icons/hicolor/scalable/filesystems/gnome-fs-trash-empty.svg"
full_icon="$XDG_DATA_DIRS/icons/hicolor/scalable/filesystems/gnome-fs-trash-full.svg"

else

empty_icon="$XDG_DATA_DIRS/icons/hicolor/scalable/filesystems/fs-trash-empty.svg"
full_icon="$XDG_DATA_DIRS/icons/hicolor/scalable/filesystems/fs-trash-full.svg"

fi

else

gnome=`find "$XDG_DATA_DIRS/icons/hicolor/48x48/filesystems" -name gnome*`

if [ "$gnome" != "" ]; then

empty_icon="$XDG_DATA_DIRS/icons/hicolor/48x48/filesystems/gnome-fs-trash-empty.png"
full_icon="$XDG_DATA_DIRS/icons/hicolor/48x48/filesystems/gnome-fs-trash-full.png"

else

empty_icon="$XDG_DATA_DIRS/icons/hicolor/48x48/filesystems/fs-trash-empty.png"
full_icon="$XDG_DATA_DIRS/icons/hicolor/48x48/filesystems/fs-trash-full.png"

fi

fi
fi

########### End of Set Trash icon ##################
####################################################

# Check if zenity is installed.
if !which zenity &> /dev/null; then
if which xmessage &> /dev/null; then
xmessage -buttons "Ok" -center "$txt1"
else
echo "$txt1"
fi
exit
fi

# Create the Trash directory if it doesn't already exist.
if  [ "$XDG_DATA_HOME" != "" ]; then
    trash=$XDG_DATA_HOME/Trash
else
    trash=$HOME/.local/share/Trash
fi

[ -d $trash/files ] || mkdir -p $trash/files
[ -d $trash/info ] || mkdir -p $trash/info

# Create the Trash interface if it doesn't already exist
if  [ "$XDG_CONFIG_HOME" != "" ]; then
    interface=$XDG_CONFIG_HOME/ROX-Trasher
else
    interface=$HOME/.config/ROX-Trasher
fi

[ -d $interface ] || mkdir -p $interface




function EmptyIcon
{
ln -sf "$empty_icon" "$APPDIR/.DirIcon"
rox -x "$APPDIR"
}

function FullIcon
{
ln -sf "$full_icon" "$APPDIR/.DirIcon"
rox -x "$APPDIR"
}

# Find the name of the file.
function notAForwardSlash
{
fSlash=/
 if [[ $1 != $fSlash ]]

  then
   return 0
  else
   return 1
 fi
}

function getFileName
{
 STRING=$1

 LENGTH=${#STRING}

 for ((n=0;n <= $LENGTH; n++))
  do
   CHAR=${STRING:$n:1}

   if notAForwardSlash $CHAR
    then
    FileName=$FileName$CHAR

   else
    FileName=""
  fi
done
}

function MoveToTrash
{
getFileName "$m"


# Add a suffix if the item is a hidden file/directory
FileName=${FileName/#./$txt2}



# Create directories for the trashed item.

# First, check if File dir exists
if test ! -e "$interface/$FileName-$$" ; then
mkdir "$interface/$FileName-$$"
fi


# Create the info file
echo "[Trash Info]
Path=$m
DeletionDate=$actual" > "$trash/info/$FileName-$$.trashinfo"


# move the item to the files Trash directory.
mv "$m" "$trash/files/$FileName-$$"

# Set the item type
  if [ -x "$trash/files/$FileName-$$/AppRun" ]; then
    filetype="rox/application"
echo "$filetype" > "$interface/$FileName-$$/type"
  else
filetype=`rox -m "$trash/files/$FileName-$$"`
echo "$filetype" > "$interface/$FileName-$$/type"
fi


filetype=`sed -e s#/#_## "$interface/$FileName-$$/type"`



#### Set Trashed icon ####
##########################

trash_icon=`find "$HOME/.config/rox.sourceforge.net/MIME-icons" -name $filetype.png`

if [ "$trash_icon" = "" ];then 
filetype=`sed -e s#/#-## "$interface/$FileName-$$/type"`

if test -e "$XDG_DATA_DIRS/icons/$theme/scalable/mimetypes"; then

gnome=`find "$XDG_DATA_DIRS/icons/$theme/scalable/mimetypes" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/$theme/scalable/mimetypes/gnome-mime-$filetype.svg"

else

trash_icon="$XDG_DATA_DIRS/icons/$theme/scalable/mimetypes/mime-$filetype.svg"

fi

else

gnome=`find "$XDG_DATA_DIRS/icons/$theme/48x48/mimetypes" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/$theme/48x48/mimetypes/gnome-mime-$filetype.png"

else

trash_icon="$XDG_DATA_DIRS/icons/$theme/48x48/mimetypes/mime-$filetype.png"

fi

fi

if [ -d "$trash/files/$FileName-$$" ];then

if [ -e "$trash/files/$FileName-$$/.DirIcon" ];then

trash_icon="$trash/files/$FileName-$$/.DirIcon"

else

if test -e "$XDG_DATA_DIRS/icons/$theme/scalable/filesystems"; then

gnome=`find "$XDG_DATA_DIRS/icons/$theme/scalable/filesystems" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/$theme/scalable/filesystems/gnome-fs-directory.svg"

else

trash_icon="$XDG_DATA_DIRS/icons/$theme/scalable/filesystems/fs-directory.svg"

fi

else

gnome=`find "$XDG_DATA_DIRS/icons/$theme/48x48/filesystems" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/$theme/48x48/filesystems/gnome-fs-directory.png"

else

trash_icon="$XDG_DATA_DIRS/icons/$theme/48x48/filesystems/fs-directory.png"

fi

fi
fi
fi

  if [ -x "$trash/files/$FileName-$$/AppRun" ]; then
if [ -e "$trash/files/$FileName-$$/.DirIcon" ]; then
trash_icon="$trash/files/$FileName-$$/.DirIcon"
else
trash_icon="/usr/lib/rox/ROX-Filer/images/application.png"
fi
fi

if test ! -e "$trash_icon"; then

theme=`grep gtk-fallback-icon-theme /etc/gtk-2.0/gtkrc | sed -e s/'gtk-fallback-icon-theme'// -e s/' '// -e s/'='// -e s/'"'// -e s/'"'//`
theme=`expr "$theme" : '[[:space:]]*\(.*\)[[:space:]]*$'`

if test -e "$XDG_DATA_DIRS/icons/$theme/scalable/mimetypes"; then

gnome=`find "$XDG_DATA_DIRS/icons/$theme/scalable/mimetypes" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/$theme/scalable/mimetypes/gnome-mime-$filetype.svg"

else

trash_icon="$XDG_DATA_DIRS/icons/$theme/scalable/mimetypes/mime-$filetype.svg"

fi

else

gnome=`find "$XDG_DATA_DIRS/icons/$theme/48x48/mimetypes" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/$theme/48x48/mimetypes/gnome-mime-$filetype.png"

else

trash_icon="$XDG_DATA_DIRS/icons/$theme/48x48/mimetypes/mime-$filetype.png"

fi
fi
fi

if test ! -e "$trash_icon"; then
if test -e "$HOME/.gtkrc-2.0"; then
theme=`grep gtk-theme-name $HOME/.gtkrc-2.0 | sed -e s/'gtk-theme-name'// -e s/' '// -e s/'='// -e s/'"'// -e s/'"'//`
theme=`expr "$theme" : '[[:space:]]*\(.*\)[[:space:]]*$'`
if  [ "$theme" = "" ];then
theme=`grep gtk-fallback-icon-theme /etc/gtk-2.0/gtkrc | sed -e s/'gtk-fallback-icon-theme'// -e s/' '// -e s/'='// -e s/'"'// -e s/'"'//`
theme=`expr "$theme" : '[[:space:]]*\(.*\)[[:space:]]*$'`
fi
else
theme=`grep gtk-fallback-icon-theme /etc/gtk-2.0/gtkrc | sed -e s/'gtk-fallback-icon-theme'// -e s/' '// -e s/'='// -e s/'"'// -e s/'"'//`
theme=`expr "$theme" : '[[:space:]]*\(.*\)[[:space:]]*$'`
fi

if test -e "$XDG_DATA_DIRS/icons/$theme/scalable/filesystems"; then

gnome=`find "$XDG_DATA_DIRS/icons/$theme/scalable/filesystems" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/$theme/scalable/filesystems/gnome-fs-regular.svg"

else

trash_icon="$XDG_DATA_DIRS/icons/$theme/scalable/filesystems/fs-regular.svg"

fi

else

gnome=`find "$XDG_DATA_DIRS/icons/$theme/48x48/filesystems" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/$theme/48x48/filesystems/gnome-fs-regular.png"

else

trash_icon="$XDG_DATA_DIRS/icons/$theme/48x48/filesystems/fs-regular.png"

fi
fi
fi


fi

if test ! -e "$trash_icon"; then


if test -e "$XDG_DATA_DIRS/icons/hicolor/scalable/mimetypes"; then

gnome=`find "$XDG_DATA_DIRS/icons/hicolor/scalable/mimetypes" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/hicolor/scalable/mimetypes/gnome-mime-$filetype.svg"

else

trash_icon="$XDG_DATA_DIRS/icons/hicolor/scalable/mimetypes/mime-$filetype.svg"

fi

else

gnome=`find "$XDG_DATA_DIRS/icons/hicolor/48x48/mimetypes" -name gnome*`

if [ "$gnome" != "" ]; then

trash_icon="$XDG_DATA_DIRS/icons/hicolor/48x48/mimetypes/gnome-mime-$filetype.png"

else

trash_icon="$XDG_DATA_DIRS/icons/hicolor/48x48/mimetypes/mime-$filetype.png"


fi
fi
fi
#### End of Set Trashed icon ####
#################################

# Link the icon for the trashed item.
ln -sf "$trash_icon" "$interface/$FileName-$$/.DirIcon"

filetype=`sed -e s#/#-## "$interface/$FileName-$$/type"`
# Create the AppInfo file
echo "<?xml version=\"1.0\"?>
<AppInfo>
  <Summary>$filetype - $appinfo1 $actual - $appinfo2 $m</Summary>
  <About>
    <$appinfo3>$filetype</$appinfo3>
    <$appinfo4>$actual</$appinfo4>
    <$appinfo5>$m</$appinfo5>
  </About>
   <AppMenu>
    <Item label=\"$appinfo6\" option=\"-restore\"/>
    <Item label=\"$appinfo7\" option=\"-delete\"/>
   </AppMenu>
</AppInfo>" > "$interface/$FileName-$$/AppInfo.xml"


# Write the new AppRun file with some variables
gawk -v var="PATH" -v name="$m" -v trash="$APPDIR" -v xdg="$trash" -v store="$interface" -v file="$FileName-$$" -v e_icon="$empty_icon" -v f_icon="$full_icon"   '{sub(var, name)}
{sub("TRASH", trash)}
{sub("XDG", xdg)}
{sub("STORE", store)}
{sub("FILE", file)}
{sub("E_ICON", e_icon)}
{sub("F_ICON", f_icon)}
{sub("TRASH", trash); print}' "$APPDIR/item-template" > "$interface/$FileName-$$/AppRun"

# Write the restore-all info
if test ! -e "$APPDIR/.restore-all" ; then
mkdir "$APPDIR/.restore-all"
fi

echo "#!/bin/bash
cd \"$interface/$FileName-$$\" 
./AppRun -restore" > "$APPDIR/.restore-all/restore-$FileName-$$"

# Make it executables
chmod 777 "$interface/$FileName-$$/AppRun"
chmod 777 "$APPDIR/.restore-all/restore-$FileName-$$"
}

function RemoveOldRoxIcon
{
if test -e $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default; then
while grep ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default
 do


  number=`grep -m 1 ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default`

  # Write the new Pinboard file with the trashed item removed.
  gawk -v var="$number" '{sub(var, ""); print}' $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default > $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default1

  # Rename the new pb_Default file
  mv $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default1 $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default

  # Restart the pinboard.
  rox -S

done
fi
}

function RemoveOldRoxIcon_Panel
{
if test -e $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default; then
while grep ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default
 do


  number=`grep -m 1 ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default`

  # Write the new Panel file with the trashed item removed.
  gawk -v var="$number" '{sub(var, ""); print}' $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default > $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default1

  # Rename the new pan_Default file
  mv $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default1 $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default

  # Restart the panel.
  rox -S

done
fi
}

if [ "$1" = "-empty" ]
then

 # See what is in the trash.
 stuff=`ls $interface`

if [ "$stuff" = "" ]; then
zenity --window-icon="$empty_icon" --error --text "$txt3"
else
 # Write the confirmation message.
zenity --window-icon="$empty_icon"  --title "$txt4" --question --text "$txt5 
$stuff"

  # If they chose to cancel.
  [ $? -eq 0 ] || exit

  # If they chose to delete.
  rm -fr "$interface/"*
  rm -fr "$APPDIR/.restore-all/"*
  rm -fr "$trash/files/"*
  rm -fr "$trash/info/"*

 EmptyIcon


fi
elif [ "$1" = "-restore-all" ]
then

 # See what is in the trash.
 stuff=`ls $interface`

if [ "$stuff" = "" ]; then
zenity --window-icon="$empty_icon" --error --text "$txt6"
else

zenity --window-icon="$empty_icon"  --warning --text "$txt7"

  # If they chose to cancel.
  [ $? -eq 0 ] || exit

cd "$APPDIR/.restore-all"

for restore in `ls`
do
`./*`
done


fi


else

 # Check to see if they clicked on the application or sent a file or directory to be deleted.
 if [ "$*" = "" ]
 then

  # If they just clicked on the icon.
  exec rox $interface

else


 # If they sent something to the trash can.
zenity --title="$txt8" --window-icon="$empty_icon" --question --text "$txt9"
if [ "$?" = "0" ]
 then

 for m in "$@"
 do

            # Check if the item can be deleted (write access).
            if [ ! -w "$m" ]; then 
                zenity --error --window-icon="$empty_icon" --text "$txt10 $m $txt11"
                continue
            fi
            
            # Check if the item can be trashed (read access).
            if [ ! -r "$m" ]; then 
                zenity --warning --window-icon="$empty_icon" --text "$txt10 $m $txt11 
$txt12"
                [ $? -eq 0 ] || continue
            fi

  # Test to see if the item is a symbolic link.
  if [ -h "$m" ]
  then

   # Write the confirmation message.
zenity --window-icon="$empty_icon" --warning --text "$txt13 $m $txt14"

  # If they chose to cancel.
  [ $? -eq 0 ] || exit

 fi
if test -e $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default; then
 match=`grep ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default`

 # Test $match to see if the item had a link to it on the pinboard.
 test "$match"
 if [ "$?" = "0" ]
 then

  # Write the confirmation message.
zenity --window-icon="$empty_icon" --warning --text "$txt15 $m
$txt16"

  # If they chose to cancel.
  [ $? -eq 0 ] || exit


 while check=`grep ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default`
 do

  OldNumber=`grep -c ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default`


# Get the filename again
getFileName "$m"


# Add a suffix if the item is a hidden file/directory
FileName=${FileName/#./$txt2}

# Create directories for the trashed item.
if test ! -e $interface/$FileName-$$; then
mkdir "$interface/$FileName-$$"
fi

# Create the shortcut file info
echo "$match" > "$interface/$FileName-$$/shortcut"

rox --RPC << EOF
<?xml version="1.0"?>
<env:Envelope xmlns:env="http://www.w3.org/2001/12/soap-envelope">
 <env:Body xmlns="http://rox.sourceforge.net/SOAP/ROX-Filer">
  <PinboardRemove>
   <Path>$m</Path>
  </PinboardRemove>
 </env:Body>
</env:Envelope>
EOF

# Check to see if the entry was removed.
NewNumber=`grep -c ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_Default`
if [ "$OldNumber" = "$NewNumber" ]
then

# If SOAP did not work then remove the icon manualy.
RemoveOldRoxIcon "$match"

fi
done
fi

fi

if test -e $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default; then
 match_panel=`grep ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default`

 # Test $match_panel to see if the item had a link to it on the panel.
 test "$match_panel"
 if [ "$?" = "0" ]
 then

  # Write the confirmation message.
zenity --window-icon="$empty_icon" --warning --text "$txt17 $m
$txt18"

  # If they chose to cancel.
  [ $? -eq 0 ] || exit


 while check=`grep ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default`
 do

  OldNumber_Panel=`grep -c ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default`


# Get the filename again
getFileName "$m"


# Add a suffix if the item is a hidden file/directory
FileName=${FileName/#./$txt2}

# Create directories for the trashed item.
if test ! -e $interface/$FileName-$$; then
mkdir "$interface/$FileName-$$"
fi

# Create the shortcut file info
side=`grep "panel side" $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default | sed -e s/'<panel side='// -e s/'"'// -e s/'">'//`
side=`expr "$side" : '[[:space:]]*\(.*\)[[:space:]]*$'`
echo "$side" > "$interface/$FileName-$$/shortcut_panel"
label=`grep ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default | sed -e s/'<icon label='// -e s/'"'// -e s/'">'// -e s^$m^^ -e s/'<\/icon>'//`
label=`expr "$label" : '[[:space:]]*\(.*\)[[:space:]]*$'`
echo "$label" >> "$interface/$FileName-$$/shortcut_panel"

rox --RPC << EOF
<?xml version="1.0"?>
<env:Envelope xmlns:env="http://www.w3.org/2001/12/soap-envelope">
 <env:Body xmlns="http://rox.sourceforge.net/SOAP/ROX-Filer">
  <PanelRemove>
<Side>$side</Side>
   <Path>$m</Path>
  </PanelRemove>
 </env:Body>
</env:Envelope>
EOF

# Check to see if the entry was removed.
NewNumber_Panel=`grep -c ">$m<" $HOME/.config/rox.sourceforge.net/ROX-Filer/pan_Default`
if [ "$OldNumber_Panel" = "$NewNumber_Panel" ]
then

# If SOAP did not work then remove the icon manualy.
RemoveOldRoxIcon_Panel "$match_panel"

fi
done
fi
fi

MoveToTrash "$m"


FullIcon
done
fi
fi
fi
